---
abstract: 'a щ（ﾟДﾟщ）Attribute...'
author:
  - 'Robert Acock <thisusedtobeanemail@gmail.com>'
build_requires:
  Moonshine::Test: '0.13'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-VariantAttribute
no_index:
  directory:
    - t
    - inc
provides:
  MooX::VariantAttribute:
    file: lib/MooX/VariantAttribute.pm
    version: '0.07'
  MooX::VariantAttribute::Role:
    file: lib/MooX/VariantAttribute/Role.pm
requires:
  Carp: '0'
  Combine::Keys: '0.04'
  Moo: '0'
  MooX::ReturnModifiers: '0.03'
  Scalar::Util: '0'
  perl: '5.006'
resources:
  repository: https://github.com/ThisUsedToBeAnEmail/MooX-VariantAttribute.git
version: '0.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
